INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('360', '200', '25', 'understærnbrædder til for og bag ende', '174.43');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('540', '200', '25', 'understærnbrædder til siderne', '261.63');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('360', '125', '25', 'overstærnbrædder til forenden', '108.90');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('540', '125', '25', 'oversternbrædder til siderne', '163.35');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('420', '73', '38', 'til z på bagside af dør', '120.13');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('270', '95', '45', 'løsholter til skur gavle', '5628');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('240', '95', '45', 'løsholter til skur sider', '56.28');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('480', '195', '45', 'Remme i sider, sadles ned i stolper', '205.44');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('600', '195', '45', 'Spær, monteres på rem', '257.70');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('300', '97', '97', 'Stolper nedgraves 90 cm. i jord', '134.85');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('210', '100', '19', 'til beklædning af skur 1 på 2', '20.16');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('540', '100', '19', 'vandbrædt på stern i sider', '51.84');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('360', '100', '19', 'vandbrædt på stern i forende', '34.56');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('600', 'tagplader monteres på spær', '633.00');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('360', 'tagplader monteres på spær', '266');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('30', 'skruer til tagplader', '441');
INSERT INTO `carport`.`material` (`length`, `width`, `description`, `price`) VALUES ('1000', '1', 'til vindkryds og spær', '339');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('190', 'til montering af spær på rem', '76.95');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('190', 'til montering af spær på rem', '76.95');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('60', '60', '4.5', 'Til montering af stern&vandbrædt', '307.95');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('50', '50', '4.0', 'Til montering af universalbeslag + hulbånd', '263.95');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('120', '120', '10', 'Til montering af rem på stolper', '464');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('40', '11', '40', 'Til montering af rem på stolper', '149.50');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('70', '70', '4.5', 'til montering af yderste beklædning', '149.95');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('50', '50', '4.5', 'til montering af inderste beklædning', '160.95');
INSERT INTO `carport`.`material` (`length`, `width`, `height`, `description`, `price`) VALUES ('75', '75', '50', 'Til lås på dør i skur', '183.95');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('390', 'til skurdø', '156.95');
INSERT INTO `carport`.`material` (`length`, `description`, `price`) VALUES ('35', 'Til montering af løsholter i skur', '13.95');