@startuml
'https://plantuml.com/activity-diagram-beta

|Website|
start
:Customize;
:Signup;
|Backend|
:User Data;
|Backend|
|Database|
:Create User;
|Website|
:Login;
|Backend|
:Login System;
|Website|
:Make order;
|Backend|
:Generate Order;
|Database|
:Save Order;
|Backend|
:Storage Check;
|Website|
:Approve Order;
|Backend|
:Generate Payment;
|Website|
:Payment;
|Backend|
:Generate material list + stl file;
|Website|
:Download file;
stop

@enduml
