@startuml
'https://plantuml.com/activity-diagram-beta

|Website|
start
:Customize;
:Signup;
|Backend|
:User Data;
|Admin|
|Backend|
|Database|
:Create User;
|Website|
:Login;
:Make order;
|Database|
:Order;
|Admin|
:Storage Check +
Order confirmation;
|Website|
:Confirm order;
|Backend|
:Generate material list + stl file;
|Website|
:Download file;
stop

@enduml
