()@startuml
'https://plantuml.com/class-diagram

!pragma layout smetana

class User {
- int ID
- String firstFame
- String lastName
- String email
- int zip
- int phone
- String address
- String city
- int role
- int membership
}

class UserFacade {
+ {static} ArrayList<User> getAllUsers()
+ {static} User getUser()
+ {static} void updateUser()
+ {static} void createUser2()
+ {static} void login()
+ {static} void createZipCity();
}

class UserMapper {
# {static} ArrayList<User> getAllUsers()
# {static} User getUser()
# {static} User updateUser()
# {static} User createUser()
# {static} User login()
# {static} void createZipCity();
}

class Carport{
- int length
- int width
- Shed shed
}

class OrderItem {
- int ID
- int guantity
- int price
- String description
- AMaterial material
- int length
- int width
+ void addMaterial(Material material)
}

Enum OrderItemTask{
STERN_UPPER_ENDS
STERN_UPPER_SIDES
STERN_LOWER_ENDS
STERN_LOWER_SIDES
RIM
RIM_SHED
SHED_Z
SPAR
POLE
WATERBOARD_SIDES
WATERBOARD_ENDS
ROOF_TILE
ROOF_TILE_SCREWS
FITTING_SPAR_RIM
CROSSWIND
SCREW_STERN_WATERBOARD
SCREW_UNIVERSAL_CROWSSWIND
SCREW_RIM_POLE
SCREW_OUTER_CLOTHING
SCREW_INNER_CLOTHING
SHED_CLOTHING
SHED_DOOR_LOCK
SHED_T_HINGE
SHED_SUPPORT_POSTS_SIDES
SHED_SUPPORT_POSTS_GABLE
SHED_ANGLE_BRACKET
- String task
+ String getTask()
}

class OrderItemFacade {
+ {static} ArrayList<OrderItem> getOrderItemsByOrderId()
+ {static} void createOrderItem()
+ {static} void deleteORderItems()
}

class OrderItemMapper {
# {static} ArrayList<OrderItem> getorderItemsWoodByOrderId()
# {static} ArrayList<OrderItem> getorderItemsScrewByOrderId()
# {static} ArrayList<OrderItem> getorderItemsFittingByOrderId()
# {static} ArrayList<OrderItem> getorderItemsRoofTileByOrderId()
# {static} void createOrderItemWood()
# {static} void createOrderItemScrew()
# {static} void createOrderItemFitting()
# {static} void createOrderItemRoofTile()
# {static} boolean deleteOrderItemWood()
# {static} boolean deleteOrderItemScrew()
# {static} boolean deleteOrderItemFitting()
# {static} boolean deleteOrderItemRoofTile()
}

class Order {
- int orderID
- Timestamp timestamp
- Enum status
- int length
- int width
- int shedlength
- int shedwidth
- boolean shed
- int userID
- ArrayList<OrderItem> OrderItems
+ void AddOrderItem(Order order)
+ void AddOrderItems(ArrayList<Order> orders)
}

class OrderFacade {
+ {static} ArrayList<Order> getAllOrders()
+ {static} ArrayList<Order> getOrdersByStatus()
+ {static} Order getOrderById()
+ {static} ArrayList<Order> getOrdersByUserId()
+ {static} void createOrder()
+ {static} void approveOrder()
+ {static} void deleteOrder()
+ {static} void cancelOrder()
}

class OrderMapper {
# {static} ArrayList<Order> getAllOrders()
# {static} Order getOrderById()
# {static} ArrayList<Order> getOrdersByUserId()
# {static} void approveOrder()
# {static} boolean cancleOrder()
# {static} ArrayList<Order> getOrdersByStatus()
# {static} int createOrder()
# {static} boolean deleteOrder()
}

class MaterialFacade {
+ {static} ArrayList<Material> getAllMaterials()
+ {static} Material getMaterialById()
+ {static} Wood getWoodById()
+ {static} Screw getScrewById()
+ {static} Fitting getFittingById()
+ {static} RoofTile getRoofTileById()
+ {static} ArrayList<Wood> getAllWood()
+ {static} ArrayList<Screw> getAllScrew()
+ {static} ArrayList<Fitting> getAllFitting()
+ {static} ArrayList<RoofTile> getAllRoofTile()
}

class MaterialMapper {
# {static} ArrayList<Wood> getAllWood()}
# {static} ArrayList<Screw> getAllScrew()
# {static} ArrayList<Fitting> getAllFitting()
# {static} ArrayList<RoofTile> getAllRoofTile()
# {static} Wood getWoodById()
# {static} Screw getScrewById()
# {static} Fitting getFittingById()
# {static} RoofTile getRoofTileById()
}

class GenerateStl {
+ {static} void generateStl()
}

class OrderService {
+ {static} Order getOrderById()
+ {static} ArrayList<Order> getOrdersByStatus()
+ {static} ArrayList<Order> getAllOrders()
+ {static} ArrayList<Order> getOrdersByUserId()
+ {static} void addOrder()
+ {static} list<OrderItem> generateOrderItems()
- {static} OrderItem calculateWoodPlankLEgnthForZShape()
- {static} list<OrderItem> getShedSupports()
- {static} list<OrderItem> getWaterboard()
- {static} OrderItem getRoofTiles()
- {static} OrderItem getRoofScrews()
- {static} OrderItem getMetalBand()
- {static} OrderItem getSternScrews()
- {static} OrderItemgetFittingScrews()
- {static} OrderItem getBolts()
- {static} Orderitem getDiscs()
- {static} OrderItem getScrewsForOuterClothing()
- {static} OrderItem getScrewsForInnerClothing
- {static} OrderItem getDorrHandle()
- {static} OrderItem getHinges()
- {static} OrderItem getAngleFittings()
- {static} OrderItem getUniversalFitting()
- {static} OrderItem getRims()
- {static} OrderItem getShedClothing()
- {static} OrderItem getPoles()
- {static} OrderItem getSpars()
- {static} List<OrderItem> getUpperSterns()
- {static} List<OrderItem> getStern()
- {static} List<Wood> findSterns()
- {static} List<Wood> filterWoods()
- {static} List<Screw> filterScrews()
- {static} List<Fitting> filterFittings()
- {static} double calculatePrice()
- {static} Order updateOrder()
- {static}v void cancleOrder()
- {static} void deleteOrder()
- {static} void deleteOrderItems()
}

class UserService() {
+ {static} User login()
+ {static} User updateUser()
+ {static} void createUser()
+ {static} User getUser()
+ {static} ArrayList<User> getUser()

}

class Autthentication{
+ {static} boolean isRoleAllowed
}

class Modelling{
+ {static} void generateFiles()
- {static} void save()
- {static} Geometry3D generateMaterialList()
- {static} Geometry3D generateBuildList()
- {static} ArrayList<Spot> generateSpot()
- {static} Geometry3D generatebasicShape()
- {static} Geometry3D generateCarportPoles()
- {static} Orderitem getItem()
- {static} void yAxisPacking()
- {static} Geometry3D printing()
- {static} boolean canSpotFitInRow()
}

abstract class Material {
- int id
- String name
- int length
- double price
- String unit

}

abstract class ExtraDimensionMaterial {
- int width
- int height
}

class shed{
- int length
- int width
}

class spot{
- double hight
- double width
- Geometry3D shape
}

class RoofTile {
}

class Wood {
}

class Fitting {
}

abstract class ExtraDiameterMaterial {
- int diameter
}

class Screw {
}

Enum Status {
    PENDING
    APPROVED
    CANCELLED
}



Material <|-- ExtraDimensionMaterial
ExtraDimensionMaterial <|-- RoofTile
ExtraDimensionMaterial <|-- Wood
ExtraDimensionMaterial <|-- Fitting
Material <|-- ExtraDiameterMaterial
ExtraDiameterMaterial <|-- ScrewPack
ExtraDiameterMaterial <|-- Screw

Order *-- OrderItem
OrderItem *-- OrderItemTask
OrderItem *-- Material
Order *-- Status
User *-- Order

@enduml