@startuml
'https://plantuml.com/class-diagram

class User {
-int ID
-String firstname
-String surname
-String listorders
+String email
+int role
+int membership
}

class Order {
-int orderID
+String timestamp
+ArrayList status
+ArrayList screwList
+ArrayList woodList
+ArrayList fittingList
+ArrayList roofTileList
}

class UserMapper{
+getAllUsers()
+getUser()
+updateUser()
+deleteUser()
+createUser()
}

class OrderFacade{
updateOrder()
deleteOrder()
createOrder()
approveOrder()
}

class MaterialFacade{
addWood()
addScrews()
addRoofTiles()
addFittings()
}

class UserFacade{
updateUser()
deleteUser()
createUser()


}


class OrderMapper{
+getAllOrders()
+getOrder()
+updateOrder()
+deleteOrder()
+createOrder()
+approveOrder()
}

class MaterialMapper{
+getAllMaterials()
+getMaterial()
+addWood()
+addScrews()
+addRoofTiles()
+addFittings()

}

class RoofTiles{
+String name
+int length
+int width
+double price
+description
}

class Wood{
+String name
+int length
+int height
+int width
+double price
+String description
}

class Fittings{
+String name
+int length
+int height
+int width
+double price
+String description

}

interface AScrew{
+String name
+int length
+double price
+String description

}

class ScrewPack{
+int quantity
}

class Screw{
+int name
+double diameter
+int length
+double price
+String description
}


User <-- Order


User <-- UserFacade
UserFacade <-- UserMapper



OrderFacade <-- OrderMapper
Order <--OrderFacade


Order <-- MaterialFacade
MaterialFacade <-- MaterialMapper

MaterialMapper <-- Wood
MaterialMapper <-- Screw
MaterialMapper <-- Fittings
MaterialMapper <-- RoofTiles


AScrew <-- ScrewPack
AScrew <-- Screw

@enduml
