@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

object User
object Status
object Role
object Membership
object Order
object OrderItem
object Fittings
object Wood
object Screws
object RoofTiles

Order --> OrderItem
OrderItem --> Status
OrderItem --> Fittings
OrderItem --> Wood
OrderItem --> Screws
OrderItem --> RoofTiles

User --> Role
User --> Membership
User --> Order





@enduml
