@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

object User
object Status
object Role
object Membership
object Order
object OrderItem
object Material
object Fitting
object Wood
object Screw
object RoofTile

Order "1" -- "*" OrderItem
OrderItem "1" -- "1" Status
OrderItem "1" -- "1" Material
Material -- Fitting : is-a
Material -- Wood : is-a
Material -- Screw : is-a
Material -- RoofTile : is-a

User "1" -- "1" Role
User "1" -- "1" Membership
User "1" -- "*" Order





@enduml
