@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> Login.JSP: Username and Password
Login.JSP -> LoginServlet: Post
LoginServlet -> UserMapper: Validate
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> LoginServlet: Result
LoginServlet -> Homepage.JSP: Forward
Homepage.JSP -> User: Welcome

User -> CreateOrder.JSP: Navigate to make an order
CreateOrder.JSP -> OrderServlet: Post
OrderServlet -> OrderMapper: Validate
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> OrderServlet: Result
OrderServlet -> CreateOrder.JSP: Forward
CreateOrder.JSP -> OrderDone.JSP: Order Done
OrderDone.JSP -> User: Thanks for your order

User -> Orders.JSP: Approve order
Orders.JSP -> OrderServlet: Generate Price & Invoice
OrderServlet -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> Invoice.JSP: Invoice + materiallist + stl file


@enduml