@startuml
'https://plantuml.com/sequence-diagram

autonumber

Website -> Backend: Authentication Request
Backend --> Database: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
@enduml