@startuml
'https://plantuml.com/sequence-diagram

autonumber

'admin login'

Admin -> homepage.jsp: Forward
homepage.jsp --> login.jsp: Navigate to login
login.jsp -> LoginServlet: Post
LoginServlet -> UserService: Valid
UserService -> UserFacade: Post
UserFacade -> UserMapper : post
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> UserFacade: Result
UserFacade -> UserService: Result
UserService -> LoginServlet: Result
LoginServlet -> AdminHomepageServlet: Forward



'Grab OrderData from the database'

AdminHomepageServlet -> OrderService: Post
OrderService -> OrderFacade: Post
OrderFacade -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> OrderFacade: Result
OrderFacade -> OrderService: Result
OrderService-> AdminHomepageServlet: Result



'Grab CustomerData from the database'

AdminHomepageServlet -> UserService: Post
UserService -> UserFacade: Post
UserFacade -> UserMapper: Post
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> UserFacade: Result
UserFacade -> UserService: Result
UserService -> AdminHomepageServlet: Customer + Order Results
AdminHomepageServlet -> adminHomepage.jsp: Forward to admin homepage

@enduml