@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> AdminHomepage.JSP: Navigate to see specific order
AdminHomepage.JSP -> AdminHomepageServlet: Forward
AdminHomepageServlet -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> AdminHomepageServlet: Order data result
AdminHomepageServlet -> CustomerMapper: Post
CustomerMapper -> SQL: Query
SQL --> CustomerMapper: ResultSet
CustomerMapper -> AdminHomepageServlet: Customer + Order Results
AdminHomepageServlet -> Order.JSP: Forward to see specific order

@enduml