@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> AdminHomepage.JSP: See customer list
AdminHomepage.JSP -> CustomerServlet: Post
CustomerServlet -> UserMapper: Valid
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> CustomerServlet: Result
CustomerServlet -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> OrderServlet: Customer + Orders results
OrderServlet -> Customer.JSP: Navigate to see list of orders and customers

@enduml