@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> AdminHomepage.JSP: See customer list
AdminHomepage.JSP -> CustomerServlet: Post
CustomerServlet -> UserMapper: Valid
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> CustomerServlet: Result
CustomerServlet -> OrdersMapper: Post
OrdersMapper -> SQL: Query
SQL --> OrdersMapper: ResultSet
OrdersMapper -> OrdersServlet: Customer + Orders results
OrdersServlet -> Customer.JSP: Navigate to see list of orders and customers

@enduml