@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> AdminHomepage.JSP: Navigate to see specific order
AdminHomepage.JSP -> AdminHomepageServlet: Forward
AdminHomepageServlet -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> COServlet: Order data result
COServlet -> CustomerMapper: Post
CustomerMapper -> SQL: Query
SQL --> CustomerMapper: ResultSet
CustomerMapper -> COServlet: Customer + Order Results
COServlet -> Order.JSP: Forward to see specific order

@enduml