@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> AdminHomepage.JSP: Navigate to see specific order
AdminHomepage.JSP -> OrderServlet: Forward
OrderServlet -> OrderMapper: Post
OrderMapper -> SQL: Query
SQL --> OrderMapper: ResultSet
OrderMapper -> OrderServlet: Order data result
OrderServlet -> UserMapper: Post
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> OrderServlet: Customer + Order Results
OrderServlet -> Order.JSP: Forward to see specific order

@enduml