@startuml
'https://plantuml.com/sequence-diagram

autonumber

Admin -> Homepage.JSP: Forward
Homepage.JSP --> Login.JSP: Navigate to login
Login.JSP -> LoginServlet: Post
LoginServlet -> UserMapper: Valid
UserMapper -> SQL: Query
SQL --> UserMapper: ResultSet
UserMapper -> LoginServlet: Result
LoginServlet -> AdminHomepageServlet: Forward

AdminHomepageServlet -> OrdersMapper: Post
OrdersMapper -> SQL: Query
SQL --> OrdersMapper: ResultSet
OrdersMapper -> AdminHomepageServlet: Result
AdminHomepageServlet -> CustomerMapper: Post

CustomerMapper -> SQL: Query
SQL --> CustomerMapper: ResultSet
CustomerMapper -> AdminHomepageServlet: Customer + Order Results
AdminHomepageServlet -> AdminHomepage.JSP: Forward to admin homepage

@enduml