@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> homepage.jsp: Navigate to login
homepage.jsp -> login.jsp: Login
login.jsp -> LoginServlet: Post
LoginServlet -> UserService: Valid
UserService -> UserFacade: data
UserFacade -> UserMapper: data
UserMapper -> SQL: Query
SQL -> UserMapper: ResultSet
UserMapper -> UserFacade: User
UserFacade -> UserService: User
UserService -> LoginServlet: Result
LoginServlet -> homepage.jsp: Redirect to success page
@enduml