@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> homepage.jsp: Order Carport
homepage.jsp -> OrderServlet: Post
OrderServlet -> OrderService: Valid
OrderService -> OrderFacade:valid
OrderFacade -> OrderMapper: Valid
OrderMapper -> SQL: Query
SQL -> OrderMapper: ResultSet
OrderMapper -> OrderFacade: Result
OrderFacade -> OrderService: Result
OrderService-> OrderServlet: Result
OrderServlet -> success.jsp: Forward

@enduml