@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> Homepage.JSP: Navigate to login
Homepage.JSP -> Login.JSP: Login
Login.JSP -> LoginServlet: Post
LoginServlet -> UserMapper: Valid
UserMapper -> SQL: Query
SQL -> UserMapper: ResultSet
UserMapper -> LoginServlet: Result
LoginServlet -> Homepage.JSP: Redirect to success page
@enduml