@startuml
'https://plantuml.com/sequence-diagram

autonumber

User -> success.jsp: Navigate to signup
success.jsp -> signup.jsp: Signup
signup.jsp -> SignupServlet: Post
SignupServlet -> UserService: Create
UserService -> UserFacade: Create
UserFacade -> UserMapper: Create
UserMapper -> SQL: Query
SQL -> UserMapper: ResultSet
UserMapper -> UserFacade: User
UserFacade -> UserService: User
UserService -> SignupServlet: Result
SignupServlet -> success.jsp: Redirect to success page

@enduml